#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt

echo
echo
echo "Setup complete. Run 'develop' to start homeassistant server"

# ./scripts/develop